### ISSUE TITLE
IO issue tracking

### ISSUE THREAD

**Issue by KnutAM** [KnutAM/FerriteProblems.jl#6]
Currently, there are several parts that make the saving with JLD2 not reliable. 
The goal should be that a saved `FEDefinition` and `timestepper` (from FESolvers) suffice for recreating the simulation. 

Issues related to this are,
- [ ] Functions for loading must be available upon reload (i.e. anonymous functions not allowed). Could be partially solved with https://github.com/JuliaIO/JLD2.jl/pull/468
- [ ] Add saving of `timestepper` from `FESolvers` (and optionally the full solver)
- [x] Support do-block for opening during after simulation postprocessing
- [ ] For reproducibility, should save `Project.toml` and `Manifest.toml` (see https://github.com/invenia/JLSO.jl)
- [ ] Test setup to save things in one julia session and load things in the next session
